version: '3.8'
services:
  # Serviço para o PostgreSQL
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3308:3308"
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: animals
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_TCP_PORT: 3308
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - local

  # Serviço para a aplicação Spring Boot
  cardapio:
    build: .
    environment:
      DB_HOST: mysql
      DB_USER: dev
      DB_PASS: dev
      DB_PORT: 3308
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - local

networks:
  local:
    driver: bridge

volumes:
  mysql_data: